services:
  - type: web
    name: timetracker-pro
    env: node
    plan: free
    buildCommand: npm install && npx vite build && npx esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist && mkdir -p dist/uploads && cp -r shared dist/
    startCommand: NODE_ENV=production node dist/index.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: timetracker-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: REPLIT_DOMAINS
        value: timetracker-pro.onrender.com
      - key: ISSUER_URL
        value: https://replit.com/oidc
      - key: REPL_ID
        value: your-repl-id-here

databases:
  - name: timetracker-db
    databaseName: timetracker
    user: timetracker_user
    plan: free